config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :delete]

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: params[:user][:name])
    if @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Cheers"
    else
      redirect_to root_path, notice: "You failed"
    end
  end

  def delete
    
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new
    if @user = User.create(user_params)
        redirect_to root_path
    else
        redirect_to new_user_path
    end

    def show
    end
  end


  private def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweedeck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :confirm_password %>
<%= f.password_field :password_confirmation %>

<%= f.submit 'Sign UP!' %>

<% end %>

app/views/welcome/index.html.erb
<h1>TWEEDECK</h1>

<p>Welcome, are you new/existing? See link below</p>

<%= link_to 'New user?', new_user_path %>
<%= link_to 'Log in', new_session_path %>